### ISSUE TITLE
cannot input bam file

### ISSUE THREAD

**Issue by wzylin** [js2264/VplotR#10] opened 2021-04-19 14:38 UTC
I tried to plot the Mnase data by VplotR.
I mapped the published Mnase data (GEO: [GSM2098439](https://www.ncbi.nlm.nih.gov/sra?LinkName=biosample_sra&from_uid=4578117)) by bowtie2.
```
bowtie2_index=~/references_seq/ce11
fq1=~/jobs/3_Mnase_timecourse/raw/SRR3289719_1.fastq
fq2=~/jobs/3_Mnase_timecourse/raw/SRR3289719_2.fastq
bowtie2 -p 2 --local -x $bowtie2_index -1 $fq1 -2 $fq2 -S 2m.sam
samtools view -Sb 2m.sam > 2m.bam
samtools sort -O bam -@ 2 -o 2m.sort.bam 2m.bam 
samtools index 2m.sort.bam
```

Then I load the bam file by importPEBamFiles in R:
```
bam_file <- ('~/Mnase/2m.sort.bam')
fragments <- importPEBamFiles(
  bam_file, 
  shift_ATAC_fragments = FALSE,
)
fragments
```

However, no fragments were imported as GRanges.

```
> fragments
GRanges object with 0 ranges and 0 metadata columns:
   seqnames    ranges strand
      <Rle> <IRanges>  <Rle>
  -------
  seqinfo: 7 sequences from an unspecified genome

```
I tried other mapping parameters and also did not work.
`bowtie2  -p 10  --very-sensitive -X 2000 -x  $bowtie2_index -1 $fq1 -2 $fq2 -S ${sample}.sam`

Any idea? 

Thank you.

**Comment by js2264** [comment] 2021-04-19 16:19
Hi @wzylin, 
Sorry but I cannot reproduce the issue you are having. I downloaded the files you mentionned and mapped it with bowtie2 as you wrote. I obtained `44,117,628` reads mapping in proper pairs. 

```{shell}
# --- Dwnload data 
curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR328/009/SRR3289719/SRR3289719_1.fastq.gz -o SRR3289719_GSM2098439_RT_rep2_-_2m_MNase-seq_Caenorhabditis_elegans_MNase-Seq_1.fastq.gz
curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR328/009/SRR3289719/SRR3289719_2.fastq.gz -o SRR3289719_GSM2098439_RT_rep2_-_2m_MNase-seq_Caenorhabditis_elegans_MNase-Seq_2.fastq.gz
# --- Align 
wget http://ftp.ensembl.org/pub/release-103/fasta/caenorhabditis_elegans/dna/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa.gz
bowtie2-build --threads 12 Caenorhabditis_elegans.WBcel235.dna.toplevel.fa.gz Caenorhabditis_elegans.WBcel235.dna.toplevel
bowtie2_index=./Caenorhabditis_elegans.WBcel235.dna.toplevel
fq1=./SRR3289719_GSM2098439_RT_rep2_-_2m_MNase-seq_Caenorhabditis_elegans_MNase-Seq_1.fastq.gz
fq2=./SRR3289719_GSM2098439_RT_rep2_-_2m_MNase-seq_Caenorhabditis_elegans_MNase-Seq_2.fastq.gz
bowtie2 --threads 12 --local -x $bowtie2_index -1 $fq1 -2 $fq2 -S 2m.sam
# --- Sort 
samtools view -Sb 2m.sam > 2m.bam
samtools sort -O bam -@ 12 -o 2m.sort.bam 2m.bam 
samtools index 2m.sort.bam
# --- Check stats 
samtools stats /data/scratch/tmp_vplotr/2m.sort.bam | grep ^SN | cut -f 2-
```

```{shell}
raw total sequences:	44328436
filtered sequences:	0
sequences:	44328436
is sorted:	1
1st fragments:	22164218
last fragments:	22164218
reads mapped:	44188371
reads mapped and paired:	44155396	# paired-end technology bit set + both mates mapped
reads unmapped:	140065
reads properly paired:	44117628	# proper-pair bit set
...
```

When I import this in R using `importPEBamFiles()`, it recovers the fragments: 

```{r}
bam_file <- '2m.sort.bam'
fragments <- importPEBamFiles(
  bam_file,
  shift_ATAC_fragments = FALSE,
)
> Importing 2m.sort.bam ...
> Filtering 2m.sort.bam ...
> 2m.sort.bam import completed.
fragments
GRanges object with **22058814** ranges and 0 metadata columns:
             seqnames      ranges strand
                <Rle>   <IRanges>  <Rle>
         [1]        I       1-196      +
         [2]        I       1-232      +
         [3]        I       1-424      +
         [4]        I       1-244      +
         [5]        I       4-106      +
         ...      ...         ...    ...
  [22058810]    MtDNA 13164-13371      -
  [22058811]    MtDNA 13181-13373      -
  [22058812]    MtDNA 13181-13373      -
  [22058813]    MtDNA 13467-13588      +
  [22058814]    MtDNA 13682-13794      +
  -------
  seqinfo: 7 sequences from an unspecified genome
```

Two things: 
1) Did you make sure that your `sam` file contains what you think it should (I get ~ 44M reads, so ~22M pairs). 
2) Do you have any error message when running `importPEBamFiles` ? You should get few lines of messages telling you that the file is being imported, and it probably takes a good 5 minutes on a local machine to run. 

From your output, I have the feeling that you have an empty `sam` file: the `GenomicRanges` object does know that there are 7 seqnames so the `sam` header must be right. But perhaps the `sam` is otherwise empty? I'd advise to first run a `samtools stats` to be sure that the `sam` file has reads and proper pairs. 

Also, I'd recommend using the `dev` version of `VplotR` (install it with `devtools::install_github('js2264/VplotR')`, as it contains several fixes that are not yet in the latest Bioconductor release. 

Let me know once this is done!

**Comment by wzylin** [comment] 2021-04-21 11:18
> Hi @wzylin,
> Sorry but I cannot reproduce the issue you are having. I downloaded the files you mentionned and mapped it with bowtie2 as you wrote. I obtained `44,117,628` reads mapping in proper pairs.
> 
> ```
> # --- Dwnload data 
> curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR328/009/SRR3289719/SRR3289719_1.fastq.gz -o SRR3289719_GSM2098439_RT_rep2_-_2m_MNase-seq_Caenorhabditis_elegans_MNase-Seq_1.fastq.gz
> curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR328/009/SRR3289719/SRR3289719_2.fastq.gz -o SRR3289719_GSM2098439_RT_rep2_-_2m_MNase-seq_Caenorhabditis_elegans_MNase-Seq_2.fastq.gz
> # --- Align 
> wget http://ftp.ensembl.org/pub/release-103/fasta/caenorhabditis_elegans/dna/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa.gz
> bowtie2-build --threads 12 Caenorhabditis_elegans.WBcel235.dna.toplevel.fa.gz Caenorhabditis_elegans.WBcel235.dna.toplevel
> bowtie2_index=./Caenorhabditis_elegans.WBcel235.dna.toplevel
> fq1=./SRR3289719_GSM2098439_RT_rep2_-_2m_MNase-seq_Caenorhabditis_elegans_MNase-Seq_1.fastq.gz
> fq2=./SRR3289719_GSM2098439_RT_rep2_-_2m_MNase-seq_Caenorhabditis_elegans_MNase-Seq_2.fastq.gz
> bowtie2 --threads 12 --local -x $bowtie2_index -1 $fq1 -2 $fq2 -S 2m.sam
> # --- Sort 
> samtools view -Sb 2m.sam > 2m.bam
> samtools sort -O bam -@ 12 -o 2m.sort.bam 2m.bam 
> samtools index 2m.sort.bam
> # --- Check stats 
> samtools stats /data/scratch/tmp_vplotr/2m.sort.bam | grep ^SN | cut -f 2-
> ```
> 
> ```
> raw total sequences:	44328436
> filtered sequences:	0
> sequences:	44328436
> is sorted:	1
> 1st fragments:	22164218
> last fragments:	22164218
> reads mapped:	44188371
> reads mapped and paired:	44155396	# paired-end technology bit set + both mates mapped
> reads unmapped:	140065
> reads properly paired:	44117628	# proper-pair bit set
> ...
> ```
> 
> When I import this in R using `importPEBamFiles()`, it recovers the fragments:
> 
> ```
> bam_file <- '2m.sort.bam'
> fragments <- importPEBamFiles(
>   bam_file,
>   shift_ATAC_fragments = FALSE,
> )
> > Importing 2m.sort.bam ...
> > Filtering 2m.sort.bam ...
> > 2m.sort.bam import completed.
> fragments
> GRanges object with **22058814** ranges and 0 metadata columns:
>              seqnames      ranges strand
>                 <Rle>   <IRanges>  <Rle>
>          [1]        I       1-196      +
>          [2]        I       1-232      +
>          [3]        I       1-424      +
>          [4]        I       1-244      +
>          [5]        I       4-106      +
>          ...      ...         ...    ...
>   [22058810]    MtDNA 13164-13371      -
>   [22058811]    MtDNA 13181-13373      -
>   [22058812]    MtDNA 13181-13373      -
>   [22058813]    MtDNA 13467-13588      +
>   [22058814]    MtDNA 13682-13794      +
>   -------
>   seqinfo: 7 sequences from an unspecified genome
> ```
> 
> Two things:
> 
> 1. Did you make sure that your `sam` file contains what you think it should (I get ~ 44M reads, so ~22M pairs).
> 2. Do you have any error message when running `importPEBamFiles` ? You should get few lines of messages telling you that the file is being imported, and it probably takes a good 5 minutes on a local machine to run.
> 
> From your output, I have the feeling that you have an empty `sam` file: the `GenomicRanges` object does know that there are 7 seqnames so the `sam` header must be right. But perhaps the `sam` is otherwise empty? I'd advise to first run a `samtools stats` to be sure that the `sam` file has reads and proper pairs.
> 
> Also, I'd recommend using the `dev` version of `VplotR` (install it with `devtools::install_github('js2264/VplotR')`, as it contains several fixes that are not yet in the latest Bioconductor release.
> 
> Let me know once this is done!

Thank you for your help! It works now.

I think the problem might be from the SRR files I download from NCBI.
Although the samstat shows that mostly of the mapped reads as pairs, the reads in bam file did not show as pairs  IGV.
The fastq files downloaded from ebi do not have such problem.

**Comment by js2264** [comment] 2021-04-21 11:20
Glad to hear that! I'll close the issue now, but don't hesitate to re-open it if you have other issues related to this one. 
Cheers, 
J

**Closed as completed by js2264** 2021-04-21 11:20 UTC
